steps:
- name: 'gcr.io/cloud-builders/gcloud' # Use gcloud image
  entrypoint: 'bash'  # Set entrypoint to bash for easier scripting
  args:
  - '-c'
  - |
    echo "$_GOOGLE_APPLICATION_CREDENTIALS" > GOOGLE_APPLICATION_CREDENTIALS.json
    # Your other build steps here...
  secretEnv: ['GOOGLE_APPLICATION_CREDENTIALS']
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/firebase-service-account-key/versions/latest
    env: 'GOOGLE_APPLICATION_CREDENTIALS'

# Add other build steps as needed (e.g., Docker build)
